### PR TITLE
Fix multi query with filter result error

### PR DESCRIPTION
**Pull request by ted-wq-x**
query like `match (a:Person) match (b:Person) where a.firstName=b.firstName and a.lastName="Chen" return a limit 1;` result error, filter `a.lastName='Chen' ` is not effective

### CODE REVIEW

**Review by andyfengHKU — APPROVED** [review]
Hi @ted-wq-x, thanks for the fix. I made a few changes to simplify the code a bit. Once CI passes we are good to go.

**Comment by ted-wq-x** [comment]
> Hi @ted-wq-x, thanks for the fix. I made a few changes to simplify the code a bit. Once CI passes we are good to go.

my fault, ut CrossJoinWithFilterPushDownTest query should be `MATCH (a:person) MATCH (b:person) where a.fName=b.fName and a.fName is null RETURN a.gender` ,in this case ,filter should be pushed down

**Comment by andyfengHKU** [comment]
> > Hi @ted-wq-x, thanks for the fix. I made a few changes to simplify the code a bit. Once CI passes we are good to go.
> 
> my fault, ut CrossJoinWithFilterPushDownTest query should be `MATCH (a:person) MATCH (b:person) where a.fName=b.fName and a.fName is null RETURN a.gender` ,in this case ,filter should be pushed down

Whoops I see. I'll do with a separate PR.

**Comment by andyfengHKU** [comment]
> > > Hi @ted-wq-x, thanks for the fix. I made a few changes to simplify the code a bit. Once CI passes we are good to go.
> > 
> > 
> > my fault, ut CrossJoinWithFilterPushDownTest query should be `MATCH (a:person) MATCH (b:person) where a.fName=b.fName and a.fName is null RETURN a.gender` ,in this case ,filter should be pushed down
> 
> Whoops I see. I'll do with a separate PR.

Fix should be available in #3336

**Pull request merged**
