### PR TITLE
fix floating to int128 and negative to int128

### PR DESCRIPTION
**Pull request by Ashleyhx**
fix https://github.com/kuzudb/kuzu/issues/2334

### CODE REVIEW

**Review by AEsir777 — COMMENTED** [review]
`Return cast(-170141183460469231731687303715884105728, "int128")` reports error `Cast failed. 170141183460469231731687303715884105728 is not within INT128 range.` while -170141183460469231731687303715884105728 should be the smallest INT128 value.

**Review by acquamarin — APPROVED** [review]

**Comment by Ashleyhx** [comment]
> `Return cast(-170141183460469231731687303715884105728, "int128")` reports error `Cast failed. 170141183460469231731687303715884105728 is not within INT128 range.` while -170141183460469231731687303715884105728 should be the smallest INT128 value.

I think we only allow -170141183460469231731687303715884105727 to 170141183460469231731687303715884105727 to avoid possible overflows.

**Comment by acquamarin** [comment]
```
D select cast(-170141183460469231731687303715884105728 as  hugeint);
Error: Conversion Error: Type DOUBLE with value -1.7014118346046923e+38 can't be cast because the value is out of range for the destination type INT128
```
Looks like duckdb fails in this number. Not sure what is the limit.

**Comment by Ashleyhx** [comment]
> ```
> D select cast(-170141183460469231731687303715884105728 as  hugeint);
> Error: Conversion Error: Type DOUBLE with value -1.7014118346046923e+38 can't be cast because the value is out of range for the destination type INT128
> ```
> 
> Looks like duckdb fails with this number. Not sure what is the limit.

limit is -170141183460469231731687303715884105727 not -170141183460469231731687303715884105728. otherwise it will fail [here](https://github.com/duckdb/duckdb/blob/main/src/common/types/hugeint.cpp#L339) for duckdb.

**Comment by AEsir777** [comment]
> > ```
> > D select cast(-170141183460469231731687303715884105728 as  hugeint);
> > Error: Conversion Error: Type DOUBLE with value -1.7014118346046923e+38 can't be cast because the value is out of range for the destination type INT128
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Looks like duckdb fails with this number. Not sure what is the limit.
> 
> limit is -170141183460469231731687303715884105727 not -170141183460469231731687303715884105728. otherwise it will fail [here](https://github.com/duckdb/duckdb/blob/main/src/common/types/hugeint.cpp#L339) for duckdb.

Ah, okay. So maybe we need to modify the error message? `170141183460469231731687303715884105728 is not within INT128 range.` or just leave it as it is.

**Pull request merged**
