### PR TITLE
Fix cmake configuration

### PR DESCRIPTION
**Pull request by yixinglu**
`COMMAND_ERROR_IS_FATAL` was introduced in cmake 3.19, see [here](https://discourse.cmake.org/t/execute-proces-interaction-between-command-error-is-fatal-and-timeout/2303) for details. This is inconsistent with the cmake minimum required version `3.11`.

**I have read and agree to the terms under [CLA.md](https://github.com/kuzudb/kuzu/blob/master/CLA.md).**

### CODE REVIEW

**Comment by yixinglu** [comment]
@benjaminwinger I know that the `CMAKE_EXPORT_COMPILE_COMMANDS` option can be modified by environment variable or cmake argument, because the corresponding `compile_commands.json` file is always generated in the build directory, and the build directory is ignored, so it is no problem to turn on it by default. However, I have removed this change, please review this PR again.  Thanks.

**Comment by benjaminwinger** [comment]
Okay, sounds good.

Also, since this is your first time contributing to this repository, you need to agree to the contributor license agreement (see [here](https://github.com/kuzudb/kuzu/blob/master/CONTRIBUTING.md#agreeing-to-the-contributor-agreement)) (I guess it doesn't actually say that you have to do so explicitly, but stating it explicitly in your PR lets us know that you've read and understand that part).

**Review by benjaminwinger — APPROVED** [review]

**Comment by mewim** [comment]
@yixinglu Could you please take a look at our CLA at https://github.com/kuzudb/kuzu/blob/master/CLA.md and add a sentence "I have read and agree to the terms under CLA.md." to your PR description if it looks good to you? Once you agree with the CLA we can get this PR merged. Thank you.

**Comment by yixinglu** [comment]
> @yixinglu Could you please take a look at our CLA at https://github.com/kuzudb/kuzu/blob/master/CLA.md and add a sentence "I have read and agree to the terms under CLA.md." to your PR description if it looks good to you? Once you agree with the CLA we can get this PR merged. Thank you.

done

**Pull request merged**
