### PR TITLE
Use a clock-based Buffer Manager eviction strategy

### LINKED ISSUE #2137: Buffer Manager Eviction Rework
## Overview
Currently we adopt a queue-based eviction policy. A concurrent queue is used to keep track of all marked pages as eviction candidates. This poses overheads to `unpin`, as each call of this function needs to switch unlocked pages to marked, and add it to the eviction queue. 

The alternative solution described in [Virtual-Memory Assisted Buffer Management](https://dl.acm.org/doi/abs/10.1145/3588687)[^1] is to store all cached page identifiers in a fixed-size open addressing hash table. The size of the hash table is equal to the number of pages in DRAM (bounded by buffer manager memory limit). Instead of accessing eviction queue in each `unpin`, hash table is not accessed during cache hits and unpin, but only during page faults and eviction.
Moreover, the hash table makes it easier to loop over, and clean up page states from BM as we sometimes need to ` removeFilePagesFromFrames`.

This issue proposes to replace the concurrent queue with a fixed-size hash table.

## Page State and Eviction
The design of our buffer manager follows *vmCache*. See Section 3 in paper [Virtual-Memory Assisted Buffer Management](https://dl.acm.org/doi/abs/10.1145/3588687) for detailed description.

### Page State
Each page is associated with a 64-bit state entry. The entry encodes both state and version counter. 56 bits are used for the version counter. and the left 8 bits are used for state, including LOCKED, UNLOCKED, MARKED, EVICTED. Any page must be in one of these four states. The version counter is used for optimistic read. See our [code comment](https://github.com/kuzudb/kuzu/blob/4aa1d07812665b5b1067e065d40359ad7f037118/src/include/storage/buffer_manager/buffer_manager.h#L71-L162) here for more details .

### Eviction Algorithm
This issue proposes to implement hash table-based CLOCK algorithm.
The key idea is to find an old page to evict, not necessarily the oldest. We loop through cached pages in the hash table until we find one that hasn't been referenced since the last time we check it.

Eviction happens at batches of 64 pages at a time, and is performed in five steps:
1. loop over the hash table, and get a batch of marked candidates from hash table.
2. write dirty pages (optionally, this can be done with async io).
3. try to lock clean page candidates.
4. remove locked pages from page table using `madvise`.
5. remove locked pages from eviction hash table, unlock them.

Note: Currently, we already ensure dirty pages are locked. No need to lock and upgrade dirty pages as described in `vmcache`.

See code [here](https://github.com/viktorleis/vmcache/blob/28dcacfaf94dcb34a0cecd8514e87fdbadd22dc1/vmcache.cpp#L743) for implementation details in `vmcache`.

### Changes to BM
1. Remove `addToEvictionQueue` from `unpin` .
2. Rework `claimAFrame` to be on top of the hash table based batch eviction.

### Suggested Testings
As BM is critical to the system, and complicated enough to be not easily tested. We suggest following ways (but not limited to these) to test it when open an PR to fix this issue. Using `logger` is a good way to ensure the correctness of the algorithm. Also, set eviction batch size to 1 can simplify log tracing.

**Existing tests**
After changes, existing tests should still be able to pass (`make test`).

**Small BM size**
Try to set BM to a very small size to ensure BM can correctly bookkeep memory usage. For example, running query `MATCH (c:Comment) RETURN min(c.length)` requires two pinned 256KB pages, and one an extra 4KB page should be enough to evaluate the query on LDBC1 comment table with a single thread.

**Repeated query with large BM size**
Given enough BM buffer, running the same query twice: the first run will trigger cache of all necessary pages, and the second run will trigger no reads from files, and no evictions; or running the same query concurrently: each page should only be read once from file, and no evictions are triggered.

**Repeated query with limited BM size**
Given limited BM buffer, for example, around half of needed disk pages, running the same query twice. The first run will trigger read of all pages from file, and also evictions of around half of pages read from file. The second run will also trigger eviction of pages read from the first run, and re-read pages from files. If carefully designed, it's possible to see each  page is read twice from file, and evicted at least once.

**Detailed CLOCK behaviour tracing**
Given a small BM buffer, for example, 1MB, run a simple scan query (for example, `MATCH (c:Comment) RETURN min(c.length)`) in single thread, and log changes to states of pages (e.g., `pin` a page to LOCKED and add it into hash table, `unpin` a page to UNLOCKED, marking unlocked pages to MARK, lock marked pages to evict them, remove evicted pages and unlock them, etc.) and clock hand position in the cache hash table. The tracing should be able to be verified with careful simulation of CLOCK behaviour.

**Large scale queries on LDBC100**
Run our benchmark queries on LDBC100 dataset to validate it works on some level of large scale dataset with multiple threads.

[^1]: Leis, Viktor, et al. "Virtual-Memory Assisted Buffer Management." SIGMOD'23.

### PR DESCRIPTION
**Pull request by benjaminwinger**
Instead of queueing potential pages to evict when unpinning, all pages currently in memory are kept in the evictionqueue. When more space is needed, pages are evicted if they haven't changed since the last time we scanned them. The eviction queue is now only accessed when fetching pages from disk and has no global lock.

Fixes #2137

Based on the hash table implementation in the VMCache paper, except that we store page states by reference and for simplicity store the eviction candidates in a circular buffer instead of a hash table since lookups aren't necessary.

While this isn't the first place we're using atomics, GCC at least depends on libatomic for 16-byte compare and swap because it's not generating the 16-byte compare exchange instruction (cmpxchg16b) directly (see [the open bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94649), and also the [atomic docs](https://gcc.gnu.org/wiki/Atomic/GCCMM/LIbrary)). Even with libatomic, it won't use cmpxchg16b without custom flags and instead uses a fallback (the `-mcx16` flag is for this specifically, but `-march=native` will also enable it if your CPU supports it or `-march=x86_64-v2` or newer). Benchmarks with `-mcx16` were almost identical, so I don't think this is much of a bottleneck (using 8-byte atomic eviction and insertion cursors should make it rare that two different threads are trying to evict or insert to the same spot anyway).

Performance improvements are minimal when there is plenty of buffer room.
I tried running some large copy benchmarks (two copies of 60M integers) with a restricted buffer, and found that the master version kept throwing buffer manager exceptions if I didn't give it a buffer pool of at least 1.5GB. With this version it works with the minimum buffer pool size of 64MB, and there was also a significant performance improvement when running this version with a 1.5GB buffer pool compared to the original.

Benchmarks are fairly rough; I ran each at least twice and averaged them (times are the first/second copies, each of 60M integers).

|   | master (ba0a6020e610) | this pr (07fcd85f) |
| ------------- | ------------- | -- |
| Unrestricted BufferPoolSize (~38GB)  | 4.4s/8.0 s  | 4.4s/7.8s | 
| BufferPoolSize = 1.5GB | 4.5s/23s  | 4.4s/13s |
| BufferPoolSize = 64MB | exception | 4.9s/24s |

### CODE REVIEW

**Comment by ray6080** [comment]
Can u also benchmark on some pure scan queries on large dataset like ldbc100 comment table? I think the cold run should be able to present performance difference.

**Review by ray6080 — APPROVED** [review]
Nice PR!

One thing to discuss here: I feel we should start to take the mem usage of the queue into consideration. BM's available memory should be `bufferPoolSize - queueSize`. Though the ratio of queue's memory usage is small, the principle is to try to make memory usage more accurate when possible and convenient. What do you think?

**Comment by benjaminwinger** [comment]
> I feel we should start to take the mem usage of the queue into consideration. BM's available memory should be bufferPoolSize - queueSize. Though the ratio of queue's memory usage is small, the principle is to try to make memory usage more accurate when possible and convenient. What do you think?

I think that's reasonable.

**Comment by benjaminwinger** [comment]
> Can u also benchmark on some pure scan queries on large dataset like ldbc100 comment table? I think the cold run should be able to present performance difference.

There is a difference, but it doesn't appear to be huge.

`MATCH (c:Comment) RETURN c.*;`:
- Before: 11.3 seconds 
- After: 10.7 seconds

`MATCH (c:Comment) RETURN max(c.content);`:
- Before: 4.9 seconds (6.0 seconds with 64MB buffer pool size)
- After: 4.5 seconds (5.5 seconds with 64MB buffer pool size)

(both run cold from a database stored on an ssd).

**Pull request merged**
