### PR TITLE
Add int16 int32 support to get_as_arrow. 

### LINKED ISSUE #1482: ge_as_arrow raise exception when use int32 or int16
i have 3 simple python test case with kuzu 0.0.3:  the only diffs are `int32`, `int16` and `int64`.  32 and 16 throws exception at `get_as_arrow`. only 64 works. 

```
def test_int32():
    db = kuzu.Database(f"./testdbs/test-{_random_id()}")
    conn = kuzu.Connection(db)
    conn.execute("CREATE NODE TABLE User(name STRING, age INT32, PRIMARY KEY (name))")
    conn.execute("CREATE (u:User {name: 'Alice', age: 35})")
    conn.execute("match(u:User) return u").get_as_arrow(chunk_size=10)


def test_int16():
    db = kuzu.Database(f"./testdbs/test-{_random_id()}")
    conn = kuzu.Connection(db)
    conn.execute("CREATE NODE TABLE User(name STRING, age INT16, PRIMARY KEY (name))")
    conn.execute("CREATE (u:User {name: 'Alice', age: 35})")
    conn.execute("match(u:User) return u").get_as_arrow(chunk_size=10)


def test_int64():
    db = kuzu.Database(f"./testdbs/test-{_random_id()}")
    conn = kuzu.Connection(db)
    conn.execute("CREATE NODE TABLE User(name STRING, age INT64, PRIMARY KEY (name))")
    conn.execute("CREATE (u:User {name: 'Alice', age: 35})")
    conn.execute("match(u:User) return u").get_as_arrow(chunk_size=10)

```
stacktrace. 
```
./testing/test_cases/test_play.py::test_int32 Failed: [undefined]RuntimeError: Unsupported Arrow type INT32
def test_int32():
        db = kuzu.Database("./testdbs/test-3")
        conn = kuzu.Connection(db)
        conn.execute("CREATE NODE TABLE User(name STRING, age INT, PRIMARY KEY (name))")
        conn.execute("CREATE (u:User {name: 'Alice', age: 35})")
>       conn.execute("match(u:User) return u").get_as_arrow(chunk_size=10)

```

### PR DESCRIPTION
**Pull request by wenhoujx**
fixes #1482 

add int16 and int32 support according to: https://arrow.apache.org/docs/format/CDataInterface.html#data-type-description-format-strings 

please let me know where is the best place to add a test for this. (I haven't touched C++ for years ... ) 

I have read and agree to the terms under CLA.md.

### CODE REVIEW

**Review by ray6080 — COMMENTED** [review]
Hi @wenhoujx , thanks for the PR!
For your question on test, we test arrow conversion in our python module, see `test_arrow.py::_test_primitive_data_types` under `tools/python_api/test`.
I would add two int32 and int16 fields to the existing query, basically modify the query to the following (`to_int32(a.age)`, `to_int16(a.age)`):
```
MATCH (a:person) RETURN a.age, to_int32(a.age), to_int16(a.age), a.isStudent, a.eyeSight, a.birthdate, a.registerTime, a.lastJobDuration, a.fName ORDER BY a.ID;
```

One comment on the changes:
Besides changes in `arrow_converter.cpp`, can you also take a look at `src/common/arrow/arrow_row_batch.cpp`? There are several switch cases are currently missing for INT16 and INT32 to make them work.
See `ArrowRowBatch::createVector`, `ArrowRowBatch::copyNonNullValue`, `ArrowRowBatch::copyNullValue`, `ArrowRowBatch::convertVectorToArray`.
If you make changes to these, things should work fine.

It's quite annoying now that many functions need to be touched for a new data type, so I probably need to do a refactoring here after this. Again, thanks for you interest, and hope to see your updates soon!

**Comment by wenhoujx** [comment]
@ray6080  thanks for the pointers, i updated the code and tests. Let me know if i need to further update. THanks !

**Comment by ray6080** [comment]
> @ray6080 thanks for the pointers, i updated the code and tests. Let me know if i need to further update. THanks !

Thanks! Looks good to me. Before merging the PR, can you manually squash your commits into one? We follow the principle of one commit for one pr, so it looks better on master commit history.
We always do `git rebase` to [squash commits in your branch into a single one](https://www.internalpointers.com/post/squash-commits-into-one-git) first, then sync local master with the latest remote (if necessary), and `git rebase master`, finally force push the branch.

**Comment by wenhoujx** [comment]
done merging into one commit.  

have you considered turn on github `merge & squash` option? https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Review by ray6080 — APPROVED** [review]

**Comment by ray6080** [comment]
> have you considered turn on github `merge & squash` option? https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

Good point, I think this will squash all commits of a pr into a single one, while we currently keep two for each. Though it doesn't matter, it's just that we didn't follow this way from day 1 😅

**Comment by wenhoujx** [comment]
y, that doesn't matter, thanks for reviewing my PR.

**Pull request merged**
