### PR TITLE
Refactor exception.h

### PR DESCRIPTION
**Pull request by Riolku**
This was the most included header in the codebase. This refactoring should help compile times.

### CODE REVIEW

**Review by ray6080 — APPROVED** [review]
LGTM. Thanks!

Let's rebase and get the benchmark CI passed before merge.

**Comment by mewim** [comment]
Please make sure that the header merge script still works (you can trigger https://github.com/kuzudb/kuzu/actions/workflows/linux-precompiled-bin-workflow.yml and test the generated lib + header) before merging.

**Comment by Riolku** [comment]
> Please make sure that the header merge script still works (you can trigger https://github.com/kuzudb/kuzu/actions/workflows/linux-precompiled-bin-workflow.yml and test the generated lib + header) before merging.

@mewim how do I test the generated lib + header?

**Comment by mewim** [comment]
> > Please make sure that the header merge script still works (you can trigger https://github.com/kuzudb/kuzu/actions/workflows/linux-precompiled-bin-workflow.yml and test the generated lib + header) before merging.
> 
> @mewim how do I test the generated lib + header?

You can follow the example in the documentation: https://kuzudb.com/docusaurus/getting-started/cpp

The dataset used is under https://github.com/kuzudb/kuzu/tree/master/dataset/demo-db/csv

**Comment by Riolku** [comment]
Tested against the example linked, works. Benchmark is now passing. I'm rerunning MSVC that hit a timeout of some kind while testing, and will merge after that.

**Pull request merged**
