### PR TITLE
Fix distinct hash table resizing

### LINKED ISSUE #3339: Query like match (a:Person) return count(distinct a) has an infinite loop problem
# DataSet
ldbc sf100

# Problem

While the  numbers of a exceeded `BaseHashTable#maxNumHashSlots`, the dead loop appears in the loop outside the method `AggregateHashTable::increaseSlotIdx`

### PR DESCRIPTION
**Pull request by acquamarin**
Closes #3339 
This PR solves a distinct hash table issue:
When we append values to distinct hash table, we forgot to resize the hashtable even if it is full. This causes an infinite loop issue.
This PR solves the issue simply by resizing the distinct hashtable upon each insertion.

### CODE REVIEW

**Comment by ted-wq-x** [comment]
This change can indeed solve the infinite loop issue,but the current hash slots has a very poor performance.

**Comment by acquamarin** [comment]
> This change can indeed solve the infinite loop issue,but the current hash slots has a very poor performance.

Since the query has `distinct` keyword in agg keys (`count(distinct a)`), we can only run the query in single thread mode. That's the reason why you were experiencing a slow spped.

**Comment by ted-wq-x** [comment]
I understand distinct only run in single thread mode, but the query in another graph db only need 2.8s (also single thread mode), in kuzu the execution didn‘t finished in 5min .

**Comment by acquamarin** [comment]
> #3339

I opened a new issue about performance: https://github.com/kuzudb/kuzu/issues/3349

**Pull request merged**
