### PR TITLE
Add windows-specific build instructions to readme

### PR DESCRIPTION
**Pull request by benjaminwinger**
Added a short description of additional requirements for building on windows to the README (see https://github.com/kuzudb/kuzu/issues/1736#issuecomment-1612130209).

### CODE REVIEW

**Review by mewim — APPROVED** [review]

**Comment by LowLevelMahn** [comment]
what "Windows" Make should be used for Windows - the 2006 GnuWin32 Version?: https://gnuwin32.sourceforge.net/packages/make.htm

**Comment by benjaminwinger** [comment]
That version might work, depending on the differences between the versions. I don't think it's been tested with that old of a version of make.

What we've used in CI is the version packaged by chocolatey: https://community.chocolatey.org/packages/make.  It looks like the person who packaged that is distributing the binaries themselves along with the package (the exe can be found [here](https://bitbucket.org/xoviat/chocolatey-packages/src/master/make/4.4.1/tools/install/bin/)).

**Comment by LowLevelMahn** [comment]
> What we've used in CI is the version packaged by chocolatey

could you add that info+url to the short build description?

**Comment by benjaminwinger** [comment]
> could you add that info+url to the short build description?

Sure. Or rather, I updated it to link chocolatey and listed the package names in an example install command, since that also includes ninja and might be a little more straightforward than linking the chocolatey packages individually. Is that sufficient?

**Comment by LowLevelMahn** [comment]
> > could you add that info+url to the short build description?
> 
> Sure. Or rather, I updated it to link chocolatey and listed the package names in an example install command, since that also includes ninja and might be a little more straightforward than linking the chocolatey packages individually. Is that sufficient?

yes - seems to be more "complete" then

**Pull request merged**
